name: example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  disk_lru_cache:
    path: ../

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
