name: disk_lru_cache
description: Disk lru cache for flutter.
version: 0.0.2
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/best-flutter/disk_lru_cache



environment:
  sdk: ">=2.0.0-dev.48.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  synchronized: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http:

flutter:
